import dns from "node:dns/promises";
dns.setServers(["1.1.1.1", "8.8.8.8"]);

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Common/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#020b0a]">
        <Navbar />

        {/* flex-1 দেওয়ার ফলে কন্টেন্ট পুরো জায়গা দখল করবে এবং ফুটার নিচে পুশ হবে */}
        <main className="flex-1 w-full">
          {children}
        </main>

        <Footer />
        <Toaster />
      </body>
    </html>
  );
}